#!/bin/bash

sudo qemu-system-x86_64 \
-enable-kvm \
-m 6144 \
-vga std \
-smp cpus=4,maxcpus=4,cores=4,threads=1,sockets=1 \
-cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
-daemonize ~/machines/windows10/disk.qcow2
