#!/bin/bash
 
sudo qemu-system-x86_64 \
-enable-kvm \
-m 8192 \
-cpu host,kvm=off,hv_time,hv_relaxed,hv_vapic,hv_spinlocks=0x1fff,hv_vendor_id=NvidiaFuckYou \
-smp cpus=2,maxcpus=4,cores=4,threads=1,sockets=1 \
-vga none \
-usb \
-device vfio-pci,host=01:00.0,multifunction=on \
-device vfio-pci,host=01:00.1 \
-drive if=pflash,format=raw,readonly,file=/usr/share/ovmf/ovmf_code_x64.bin \
-drive if=pflash,format=raw,file=/usr/share/ovmf/ovmf_vars_x64.bin \
-device usb-host,hostbus=1,hostport=6 \
-device usb-host,hostbus=1,hostport=2 \
-device usb-host,hostbus=2,hostport=1 \
-boot order=d \
-daemonize \
-drive file=/home/muru/machines/windows10/windrive.qcow2,id=disk,format=qcow2
