#!/bin/bash
 
sudo qemu-system-x86_64 \
-enable-kvm \
-m 8192 \
-cpu host,kvm=off,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
-smp cpus=4,maxcpus=4,cores=4,threads=1,sockets=1 \
-vga none \
-usb \
-device usb-host,hostbus=1,hostport=2 \
-device usb-host,hostbus=1,hostport=6 \
-device vfio-pci,host=01:00.0,multifunction=on \
-device vfio-pci,host=01:00.1 \
-drive if=pflash,format=raw,readonly,file=/usr/share/ovmf/ovmf_code_x64.bin \
-drive if=pflash,format=raw,file=/usr/share/ovmf/ovmf_vars_x64.bin \
-boot order=d \
-device virtio-scsi-pci,id=scsi \
-cdrom /home/muru/machines/windows10/win10.iso \
-drive file=/home/muru/machines/windows10/windrive.qcow2,id=disk,format=qcow2 \
-drive file=/home/muru/machines/windows10/virtio-win-0.1.141.iso,id=virtiocd,if=none,format=raw -device ide-cd,bus=ide.1,drive=virtiocd
